#!/sbin/openrc-run

name="git-http-server"
description="Git HTTP server (create/browse/delete repos)"
command="/usr/bin/python3"
command_args="/opt/git-http-server/app.py"
command_user="git"
command_background="yes"
pidfile="/run/${RC_SVCNAME}.pid"
output_log="/opt/git-http-server/server.log"
error_log="/opt/git-http-server/server.log"

depend() {
    need net
    after firewall
}

start_pre() {
    checkpath -d -o git:git /opt/git-http-server
    checkpath -f -o git:git /opt/git-http-server/server.log
}